### PR TITLE
fix: only generate pseudo selector when the selector has a match

### LINKED ISSUE #29: Pseudo classes incorrectly generated for group selectors with one pseudo match
Pseudo state classes generated by storybook-addon-pseudo-states failed to generate pseudo classes for the following:

```css
.thumb:hover,
.thumb.active {
  opacity: 100%;
  border-color: white;
} 
```

The reason for this is that the :hover indicates that a pseudo class must be generated, however the 2nd selector is used similarly. This results in invalid CSS, hence the following error is thrown at the client:

> withPseudoState.js:212 DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.thumb:hover, :host(.pseudo-hover) .thumb, .thumb.active, :host() .thumb.active { opacity: 1; border-color: white; }'.

The problem, as shown in the error is that an incorrect CSS is generated for the 2nd selector in the group, which gets an incorrect `:host()` prefix.

### PR DESCRIPTION
**Pull request by tobi-or-not-tobi**
With this change, a pseudo state selector is no longer generated for each selector inside a group. Previously, if there was a single match from a group, all selectors from the group would result in a generated pseudo state class. This would cause errors since incorrect CSS was generated. 

fixes #29

### CODE REVIEW

File: src/withPseudoState.js [hunk 1]
```diff
@@ -99,14 +99,16 @@ function rewriteStyleSheets(shadowRoot) {
...
                 const states = []
                 const plainSelector = selector.replace(matchAll, (_, state) => {
                   states.push(state)
                   return ""
                 })
                 let stateSelector
-                if (selector.startsWith(":host(") || selector.startsWith("::slotted(")) {
+                if (!matchOne.test(selector)) {
+                  return [selector]
+                } else if (selector.startsWith(":host(") || selector.startsWith("::slotted(")) {
```
Comment (ghengeveld) [inline src/withPseudoState.js:111]:
```suggestion
                }
                if (selector.startsWith(":host(") || selector.startsWith("::slotted(")) {
```

**Review by ghengeveld — APPROVED** [review]
